### ISSUE TITLE
Thanks man!

### ISSUE THREAD

**Issue by mansaj** [ElectricRCAircraftGuy/BrosTrendWifiAdapterSoftware#2]
Not an issue, just want to say thanks!! Life saver

**Comment by ElectricRCAircraftGuy** [comment]
Glad to help! This is by far the best WiFi adapter I've ever used on Linux so far. The installation is easy, which is very very very rare for Linux WiFi adapters.

**Comment by ElectricRCAircraftGuy** [comment]
How did you find this repo, by the way?

**Comment by ThakurSarveshGit** [comment]
Tried couple of days without luck and then found this repo. Works well. I searched for "Bros Trend Wifi Adapter not working on Ubuntu 18.04"!
